name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: karniv00l/platformio-run-action@v1
      with:
        environments: "teensy35,teensy36,teensy41,black_F407VE,megaatmega2561,megaatmega2560"

    - name: Upload to Speeduino server
      if: github.event_name != 'pull_request' && github.repository_owner == 'noisymime'
      env:
        WEB_PWD: ${{ secrets.WEB_PWD }}
      run: |
        curl -v https://speeduino.com:2078 || true
        curl -v --tlsv1.2 --ipv4 --user "speeduino_firmware@speeduino.com:$WEB_PWD" --basic -T "./.pio/build/megaatmega2560/firmware.hex" "https://speeduino.com:2078/bin/master.hex"
        curl -v --tlsv1.2 --ipv4 --user "speeduino_firmware@speeduino.com:$WEB_PWD" --basic -T "./.pio/build/teensy35/firmware.hex" "https://speeduino.com:2078/teensy35/master-teensy35.hex"
        curl -v --tlsv1.2 --ipv4 --user "speeduino_firmware@speeduino.com:$WEB_PWD" --basic -T "./.pio/build/teensy36/firmware.hex" "https://speeduino.com:2078/teensy36/master-teensy36.hex"
        curl -v --tlsv1.2 --ipv4 --user "speeduino_firmware@speeduino.com:$WEB_PWD" --basic -T "./.pio/build/teensy41/firmware.hex" "https://speeduino.com:2078/teensy41/master-teensy41.hex"
        curl --tlsv1.2 --ipv4 --user "speeduino_firmware@speeduino.com:$WEB_PWD" --basic -T "./reference/speeduino.ini" "https://speeduino.com:2078/master.ini"

    - name: Slack Notification (Passed)
      uses: rtCamp/action-slack-notify@v2
      if: success() && github.event_name != 'pull_request' && github.repository_owner == 'noisymime'
      env:
        SLACK_CHANNEL: git
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://avatars.githubusercontent.com/u/9919?v=4&size=48
        SLACK_TITLE: 'Firmware build was successful :white_check_mark:'
        SLACK_USERNAME: Github
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: actions url,commit

    - name: Slack Notification (Failed)
      uses: rtCamp/action-slack-notify@v2
      if: failure() && github.event_name != 'pull_request' && github.repository_owner == 'noisymime'
      env:
        SLACK_CHANNEL: git
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://avatars.githubusercontent.com/u/9919?v=4&size=48
        SLACK_TITLE: 'Firmware build FAILED :warning:'
        SLACK_USERNAME: Github
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: actions url,commit
