on:
  - push
  #- pull_request

env:
  # It's convenient to set variables for values used multiple times in the workflow.
  SKETCHES_REPORTS_PATH: sketches-reports

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          # Each element in the sequence produces a matrix job:
          - fqbn: arduino:avr:mega
            # This suffix will be used to define a unique name for the sketches report artifact.
            artifact-name-suffix: arduino-avr-mega
            family-name: arduino:avr
            platform: |
              name: arduino:avr
          - fqbn: teensy:avr:teensy35
            artifact-name-suffix: arduino-avr-teensy35
            platform: |
              source-url: https://www.pjrc.com/teensy/package_teensy_index.json
                name: teensy:avr
            family-name: teensy:avr
            source-url: https://www.pjrc.com/teensy/package_teensy_index.json

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1.1.1
        with:
          fqbn: ${{ matrix.board.fqbn }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          sketch-paths: |
            - speeduino/speeduino.ino
          verbose: true
          #platforms: |
          #  - source-url: ${{ matrix.board.source-url }}
          #    name: ${{ matrix.board.family-name }}
          platforms: |
            - ${{ matrix.board.platform }}
          libraries: |
            - name: Time

      # This step is needed to pass the size data to the report job.
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: sketches-reports-${{ matrix.board.artifact-name-suffix }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  # When using a matrix to compile for multiple boards, it's necessary to use a separate job for the deltas report
  report:
    needs: compile # Wait for the compile job to finish to get the data for the report
    if: github.event_name == 'pull_request' # Only run the job when the workflow is triggered by a pull request
    runs-on: ubuntu-latest

    steps:
      # This step is needed to get the size data produced by the compile jobs
      - name: Download sketches reports artifacts
        uses: actions/download-artifact@v4
        with:
          # All workflow artifacts will be downloaded to this location.
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}